### ISSUE TITLE
Issue on large-list scholar search

### ISSUE THREAD

**Issue by shang594** [cambialens/lens-api-doc#69]
I use the Scholar Code Samples in API,"Python - Cursor Based Pagination - List of Identifiers".But I cant get answer.
the code is "{'reference': '1152c8c9-1ba9-448e-896d-b4c4d445e122', 'message': '[terms] query does not support [lens_id]', 'code': 400}"

**Comment by rosharma9** [comment]
@shang594 The example was for brevity. You need to make sure the ids in the `"lens_id":'''+(json.dumps(ids))+'''` is passed as list. e.g. You can use something like `itertools.batched` to split the list of ids into chunks of 5000. I have pushed the updated [sample](https://docs.api.lens.org/samples-scholar.html#python---cursor-based-pagination---list-of-identifiers) that should work for you.

**Comment by shang594** [comment]
Thanks for your rapid answer. Yes,I have tried this,split ids into slices of 20. But 2k ids take 5m. I will try your method immediately.

**Comment by shang594** [comment]
I tried your method,but it's still wrong.  I passed my ids as list of 5k. This is my code and message.
`identifiers = main.read_csv_en('D:\\下载\\lens-export-readcsv.csv')   #list with almost 50k ids
# take 5000 at a time from the list and scroll for the 5000
ids = [identifiers[i:i+5000] for i in range(0,len(identifiers),5000)]
for i in range(0,len(ids)):
  request_body = '''{
      "query": {
          "terms":  {
            "lens_id":''' + (json.dumps(ids[i])) + '''
        }
      },
      "include": %s
    }''' % include

  # start recursive scrolling
  scroll(scroll_id=None,request_body=request_body)`
  
  Traceback (most recent call last):
  File "D:\project\ThesesAndPatents\test-list.py", line 52, in <module>
    scroll(scroll_id,request_body=request_body)
  File "D:\project\ThesesAndPatents\test-list.py", line 31, in scroll
    scroll_id = json['scroll_id'] # Extract the new scroll id from response
                ~~~~^^^^^^^^^^

**Comment by shang594** [comment]
And what's the meaning of "scroll id" why I should use this, if I dont use it, sth wiil be wrong?
